# Point different environments to different Drupal endpoints.
[context.production.environment]
  BASE_URL = "http://develop-gatsby-d8.pantheonsite.io/"
[context.develop.environment]
  BASE_URL = "http://develop-gatsby-d8.pantheonsite.io/"
